version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte
    ports:
      - "5173:5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
    depends_on:
      - backend
      - traefik

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3333:3333"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
    depends_on:
      - db
      - traefik

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  minio:
    image: minio/minio:latest
    ports:
      - "6000:6000"
      - "8700:8700"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --console-address ":8700"'
    depends_on:
      - traefik

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db-data:
  minio:
    driver: local
